name: voice_ai_app
description: AI-powered voice analysis app with local speech recognition and text analysis
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Audio & Speech Recognition
  record: ^6.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.4
  file_picker: ^10.2.0
  audioplayers: ^6.1.0
  
  # AI & ML
  # flutter_whisper: ^0.1.0  # Whisper integration
  # llm_toolkit: ^0.1.0      # Local LLM
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.0
  share_plus: ^11.0.0
  crypto: ^3.0.5
  
  # JSON & HTTP
  dio: ^5.7.0
  json_annotation: ^4.9.0
  
  # FFI for native integration
  ffi: ^2.1.3
  flutter_rust_bridge: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#6750A4"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
    - assets/fonts/
  
  # fonts는 google_fonts 패키지가 자동으로 처리